### ISSUE TITLE
Lista błędów

### ISSUE THREAD

**Issue by Nefarem** [FurtakM/AmRemakeMod#255]
02:
-  ~~Michaił może zrespić się przy umierającym inżynierze.~~

03:
- Można zaatakować Cornella i jego ludzi bez żadnych konsekwencji.
- Wciąż mają problem z budową budynków, i czasem Rosjanie zza drzew rozwalają im zbrojownie.
- Jeśli przerzucimy przez linię frontu co najmniej 1 osobę, wszystkie pozostałe mogą zginąć mimo że w celach wyraźnie mowa jest o min. 4 osobach.

04:
- ~~Pojawia się Frank mimo śmierci w 3 misji.~~

06:
- ~~Jeśli w 5 misji nie rozbudujemy laba, w 6 będą 2x magazynowe rozbudowy.~~

07:
- Po wczytaniu misji, przez kilka sek można mieć kontrolę nad wszystkim. (Gamma)
- Za mało randomów w momencie gdy wszyscy będą ginąć w poprzednich misjach. (Gamma)
- Generowanie 2 postaci o takich samych avatarach. (Gamma)
- Dziwne zachowanie AI czołgów z początku misji. (Tukaczewski)

08:
- ~~Przybycie z Delty randomów do Gammy jeśli Denis i Joan nie żyją.~~
- ~~Pominięcie dialogów o Joan jeśli ta zginęła w 6 misji.~~

09:
- Macmillan gada dialog "Dość Powell wydaje rozkazy [...]. " mimo że z nikt do niego nie mówił w Gammie.
- Możliwe niezrespienie się składu w Owsjence.
- Luis Gali przestaje tankować czołgi po pewnym czasie w następującej sekwencji:
     : Zgodzenie się na ofertę Arabów bez posiadania szybu w Owsjence.
     : Zbudowanie w miarę szybko szybu naftowego i poczekać aż Louis zacznie zabierać ropę.
     : W pewnym momencie się zablokuje i przestanie dalej tankować czołgi.

10:
- ~~Błąd z ładowaniem randomów lub ich tworzeniem w przypadku śmierci bohaterów drugoplanowych.~~
- ~~Respi się Gladstone pomimo śmierci w poprzednich misjach.~~
- ~~Ulepszenie ucieczki Genshera.~~
- ~~Zapisywane są Arabskie budynki.~~
- ~~Ruscy przestają budować czołgi ręcznie sterowane.~~

**Comment by FurtakM** [comment]
Błędy naprawione.
