### ISSUE TITLE
AM11

### ISSUE THREAD

**Issue by Nefarem** [FurtakM/AmRemakeMod#267]
- Jak przejmiesz bunkier w bezie przeciwnika i wsadzisz tam jednostki to otrzymują polecenia żeby iść do wieżyczek itd.
- Po zniszczeniu tej pierwszej bazy na lewo i wybicu wszystkich jednostek nadal tam żołnierze przychodzą miny podkładać.
- jak nie przejmiesz pierwszego składu to nie załącza ci się żaden limit czasowy + ataki.
- wieża transmisyjna (kontrolowana przez gracza) arabów od razu czołgi kontroluje w sensie że od razu jak czołg wyjedzie z garażu to jest połączony i nie da się go odłączyć tak samo jest przy wsiadaniu i wysiadaniu z pojazdu

**Comment by FurtakM** [comment]
Do sprawdzenia
