### ISSUE TITLE
Am 05, 06, 07, 08

### ISSUE THREAD

**Issue by Nefarem** [FurtakM/AmRemakeMod#275]
- 6 - ~~doktor zbiera małpy mimo wybrania go - Gladstone~~
- 6 - ~~nie wszystkie postacie pojawiają się w panelu na końcu~~
- 7 - sam gatlingi na przejeździe do głównej bazy?
- 7 - Dodatkowo można strzelać do zwiadowcy i go zabić, chyba wypadałoby to wyeliminować.
- 9 - dialog po to tu jesteśmy pojawia się dwa razy - cutscenka w gammie
- 9 - można zablokować skład - to blokuje wymianę z arabami i misja nie idzie dalej

**Comment by FurtakM** [comment]
"doktor zbiera małpy mimo wybrania go - Gladstone" - to dotyczy chyba misji 6.
" sam gatlingi na przejeździe do głównej bazy?" - ?

**Comment by Nefarem** [comment]
" sam gatlingi na przejeździe do głównej bazy?" - Dobra już widzę, że uzbrojenie wieżyczek jest generowane losowo. W sumie spoko, ale jak główny przejazd (prosto główną drogą) był uzbrojony w samie gatlingi to trochę za łatwo mimo wszystko.

- Dodatkowo można strzelać do zwiadowcy i go zabić, chyba wypadałoby to wyeliminować.
