### ISSUE TITLE
Am 02, 03, 04, 06, 07, 08, 09, 10, 11

### ISSUE THREAD

**Issue by Nefarem** [FurtakM/AmRemakeMod#301]
Misja 2:
- ~~Paul Khattam tylko w dialogach przemawia swoim głosem, a później w czasie gry już nie.~~

Misja 3:
- Andy Cornell opierdziela się. Przynajmniej by jakoś rozbudował bazę i stworzył jakieś pojazdy, a nie atakował tak na przypał. 
![obraz](https://user-images.githubusercontent.com/33377304/52901330-a02ae580-3202-11e9-95c7-3772532c862b.png)

Misja 4:
- ~~gdy opuściłem bazę gamma i zacząłem się rozbudowywać po lewej stronie po przejęciu składu od Rosjan, to co najmniej jeden atak „pomarańczowych” po prostu sobie stał w opustoszałej bazie Gamma. Dopiero jakiś kolejny wziął się do roboty i niszczył puste budynki.~~

Misja 6:
- ~~jeśli zbuduje po lewej stronie od punktu startu przy drzewach np. dwa budynki koszarów obok siebie tak, aby blokować przejazd, to pojazdy Rosjan od lewej strony jakoś nie chętnie będą atakowały albo po prostu będą stały nie daleko,~~
- ~~natomiast jeśli chodzi o ataki piechoty z lewej strony, to jeden z takich ataków miał chyba przy sobie naukowców, którzy no cóż byli trochę za daleko albo podleczyć rannych żołnierzy i później jedynie tylko czekali na swoją śmierć :D.~~

Misja 7:
Scenka w Bazie Gamma:
- raz dialog nie chciał ruszyć, ponieważ prawdopodobnie MacMillan natrafił na przeszkodę w postaci innych ludzi,  - S: jaki dialog?
- ~~trafiło się też tak, że w bunkrze zamiast jakiegokolwiek żołnierza był naukowiec.~~

Już sama misja:
- ~~w dialogach przemawiał Forsyth, a ostatecznie w krzakach kryła się Yamoko (to tak celowo?, bo w drugiej misji Forsyth mi nie zginął tylko po prostu się później nie pojawił),~~
- ~~trochę za dużo ludzi przeciwnika, bo chyba właśnie o to chodziło w tej misji?.~~

Misja 8:
- ~~Taka trochę pierdoła, ale gdy przybył MacMillan z ludźmi, to powiedzmy, że jakaś inna losowa postać siedziała w pojazdach, które przybyły niż ta która w poprzedniej misji kierowała nim, gdy była w tamtej czerwonej strefie. Fajnie by było, gdyby przynajmniej w tych pojazdach kierowcą był mechanik,~~
- ~~Rosjanie nie uciekli poza mapę. ~~
![obraz](https://user-images.githubusercontent.com/33377304/52901342-c94b7600-3202-11e9-90bd-554db2e1fc0c.png)

Misja 9:
- ~~ten atak Sikorskiego w scence mógłby jakoś lepiej wyglądać, bo kilkakrotnie sprawdzałem i raz na kilka razy wygląda tak w miarę, ale zawsze atakuje co najmniej kilka sekund przed resztą oddziału,~~ S: co znaczy lepiej?
- ~~czasami Van Houten się nie pojawiał,~~ - S: potrzeba więcej info.
- po przekazaniu drugi raz surowców dla przyjaciół „terrorystów” nie dostaje super tajnych informacji, a przez to nie otrzymuje medalu.

Misja 10:
- ~~nie można jakoś inaczej załatwić sprawy z tym, aby gracze nie blokowali budynków arabów? Ledwo jakiś ziomek wejdzie na teren ich bazy i koniec,~~
- ~~podobno arabscy zdrajcy uciekli, ale chyba w moim przypadku była to tylko jedna małpa.~~

Misja 11:
- ~~jak niby zdobyć medal za „zadanie poważnych strat przeciwnikowi”?~~ - S: trzeba zniszczyć większość budynków.
- ~~rozumiem że „przyjaciela” już nie ma?~~ - S: jest.
- ~~ogólnie przydałaby by się jeszcze jakakolwiek pomoc od „nowych przyjaciół” oprócz jakiś mini ataków w jednej bazie.~~ S: nie, to celowe działanie.

**Comment by FurtakM** [comment]
"    * po przekazaniu drugi raz surowców dla przyjaciół „terrorystów” nie dostaje super tajnych informacji, a przez to nie otrzymuje medalu." - potrzebuje więcej informacji jak to powtórzyć.
